title: Gloss'd
description: >
  Book reviews and writing.
baseurl: "/glossd"
url: "https://jamie-reece.github.io"
paginate:	3 # The number of posts to show per page on your homepage
name: "Jamie Bowman"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
include: ['_pages']
